import { atom } from "recoil";

export const teacherAttendanceState = atom({
    key : 'teacherAttendanceState' , 
    default :[
        { id: 1, name: "John", attendance: 85, msg: "Clear" },
        { id: 2, name: "Emily", attendance: 92, msg: "Clear" },
        { id: 3, name: "Michael", attendance: 78, msg: "Clear" },
        { id: 4, name: "Sarah", attendance: 89, msg: "Clear" },
        { id: 5, name: "David", attendance: 95, msg: "Clear" },
        { id: 6, name: "Emma", attendance: 81, msg: "Clear" },
        { id: 7, name: "James", attendance: 88, msg: "Clear" },
        { id: 8, name: "Olivia", attendance: 90, msg: "Clear" },
        { id: 9, name: "William", attendance: 75, msg: "Defaulter" },
        { id: 10, name: "Sophia", attendance: 94, msg: "Clear" },
        { id: 11, name: "Alexander", attendance: 87, msg: "Clear" },
        { id: 12, name: "Ava", attendance: 91, msg: "Clear" },
        { id: 13, name: "Daniel", attendance: 83, msg: "Clear" },
        { id: 14, name: "Isabella", attendance: 86, msg: "Clear" },
        { id: 15, name: "Matthew", attendance: 79, msg: "Clear" },
        { id: 16, name: "Mia", attendance: 93, msg: "Clear" },
        { id: 17, name: "Ethan", attendance: 80, msg: "Clear" },
        { id: 18, name: "Charlotte", attendance: 74, msg: "Defaulter" },
        { id: 19, name: "Benjamin", attendance: 77, msg: "Clear" },
        { id: 20, name: "Amelia", attendance: 96, msg: "Clear" },
        // Remaining objects
        { id: 21, name: "Liam", attendance: 85, msg: "Clear" },
        { id: 22, name: "Ella", attendance: 92, msg: "Clear" },
        { id: 23, name: "Noah", attendance: 78, msg: "Clear" },
        { id: 24, name: "Grace", attendance: 89, msg: "Clear" },
        { id: 25, name: "Lucas", attendance: 95, msg: "Clear" },
        { id: 26, name: "Avery", attendance: 81, msg: "Clear" },
        { id: 27, name: "Mason", attendance: 88, msg: "Clear" },
        { id: 28, name: "Chloe", attendance: 90, msg: "Clear" },
        { id: 29, name: "Elijah", attendance: 75, msg: "Defaulter" },
        { id: 30, name: "Harper", attendance: 94, msg: "Clear" },
        { id: 31, name: "Logan", attendance: 87, msg: "Clear" },
        { id: 32, name: "Madison", attendance: 91, msg: "Clear" },
        { id: 33, name: "Jackson", attendance: 83, msg: "Clear" },
        { id: 34, name: "Abigail", attendance: 86, msg: "Clear" },
        { id: 35, name: "Carter", attendance: 79, msg: "Clear" },
        { id: 36, name: "Aria", attendance: 93, msg: "Clear" },
        { id: 37, name: "Henry", attendance: 80, msg: "Clear" },
        { id: 38, name: "Scarlett", attendance: 84, msg: "Clear" },
        { id: 39, name: "Gabriel", attendance: 77, msg: "Clear" },
        { id: 40, name: "Evelyn", attendance: 71, msg: "Defaulter" },
        { id: 41, name: "Jack", attendance: 65, msg: "Defaulter" },
        { id: 42, name: "Lily", attendance: 63, msg: "Defaulter" },
        { id: 43, name: "Ethan", attendance: 78, msg: "Clear" },
        { id: 44, name: "Zoe", attendance: 69, msg: "Defaulter" },
        { id: 45, name: "Owen", attendance: 95, msg: "Clear" },
        { id: 46, name: "Nora", attendance: 81, msg: "Clear" },
        { id: 47, name: "Jacob", attendance: 88, msg: "Clear" },
        { id: 48, name: "Emma", attendance: 90, msg: "Clear" },
        { id: 49, name: "Luke", attendance: 75, msg: "Defaulter" },
        { id: 50, name: "Mia", attendance: 94, msg: "Clear" },
        { id: 51, name: "Evan", attendance: 87, msg: "Clear" },
        { id: 52, name: "Avery", attendance: 91, msg: "Clear" },
        { id: 53, name: "Logan", attendance: 83, msg: "Clear" },
        { id: 54, name: "Sophie", attendance: 86, msg: "Clear" },
        { id: 55, name: "Caleb", attendance: 79, msg: "Clear" },
        { id: 56, name: "Ava", attendance: 93, msg: "Clear" },
        { id: 57, name: "Isaac", attendance: 70, msg: "Defaulter" },
        { id: 58, name: "Hannah", attendance: 84, msg: "Clear" },
        { id: 59, name: "Ryan", attendance: 77, msg: "Clear" },
        { id: 60, name: "Chloe", attendance: 96, msg: "Clear" },
        { id: 61, name: "Daniel", attendance: 85, msg: "Clear" },
        { id: 62, name: "Grace", attendance: 92, msg: "Clear" },
        { id: 63, name: "William", attendance: 78, msg: "Clear" },
        { id: 64, name: "Aria", attendance: 89, msg: "Clear" },
        { id: 65, name: "Nathan", attendance: 65, msg: "Defaulter" },
    ]    
}) ;